### ISSUE TITLE
大佬，你这个速度咋样？，使用real-esrgan 超分单张图片

### ISSUE THREAD

**Issue by einsqing** [Sun-ZhenXing/Real-ESRGAN-android#1]
大佬，你这个速度咋样？，使用real-esrgan 超分单张图片

**Comment by Sun-ZhenXing** [comment]
别问，问就是极慢。不建议在手机上折腾了，速度和电脑差距十倍不止，而且运行的时候卡顿，手机干不了别的事情。Vulkan 在手机上未必比 CPU 快，所以这个只能称为玩具。

**Comment by einsqing** [comment]
> 别问，问就是极慢。不建议在手机上折腾了，速度和电脑差距十倍不止，而且运行的时候卡顿，手机干不了别的事情。Vulkan 在手机上未必比 CPU 快，所以这个只能称为玩具。

我在手机上测试的，1帧，onnx部署要1.5s，ncnn部署要3.2s，pytorch mobile要2.5s，不知道有没有优化思路，把耗时降到0.03s

**Comment by Sun-ZhenXing** [comment]
目前没有这方面的研究。这个项目里面的库我是在原生 ARM 设备上编译的，是原项目，迁移到 NDK 没成功。对于移动设备来说 Real-ESRGAN 还是有点大，不知道有没有做量化的。
